// 샘플 카드 데이터 (15개)
export const sampleCards = [
  {
    id: 1,
    rarity: 'COMMON',
    category: '풍경',
    owner: '미쓰손',
    description: '우리집 앞마당',
    price: '4 P',
    remaining: 0,
    outof: 5,
    imageSrc: '/assets/products/photo-card-soldout.svg',
  },
  {
    id: 2,
    rarity: 'RARE',
    category: '풍경',
    owner: '코드잇',
    description: "How Far I'll Go",
    price: '4 P',
    remaining: 1,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 3,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '스페인 여행',
    price: '4 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-two.svg',
  },
  {
    id: 4,
    rarity: 'COMMON',
    category: '풍경',
    owner: '코드잇',
    description: "How Far I'll Go",
    price: '4 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 5,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '스페인 여행',
    price: '4 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-two.svg',
  },
  {
    id: 6,
    rarity: 'LEGENDARY',
    category: '풍경',
    owner: '미쓰손',
    description: '우리집 앞마당',
    price: '4 P',
    remaining: 0,
    outof: 5,
    imageSrc: '/assets/products/photo-card-soldout.svg',
  },
  {
    id: 7,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '미쓰손',
    description: '스페인 여행',
    price: '4 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-two.svg',
  },
  {
    id: 8,
    rarity: 'COMMON',
    category: '풍경',
    owner: '미쓰손',
    description: '우리집 앞마당',
    price: '4 P',
    remaining: 0,
    outof: 5,
    imageSrc: '/assets/products/photo-card-soldout.svg',
  },
  {
    id: 9,
    rarity: 'RARE',
    category: '풍경',
    owner: '코드잇',
    description: "How Far I'll Go",
    price: '4 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 10,
    rarity: 'COMMON',
    category: '풍경',
    owner: '미쓰손',
    description: '우리집 앞마당',
    price: '4 P',
    remaining: 0,
    outof: 5,
    imageSrc: '/assets/products/photo-card-soldout.svg',
  },
  {
    id: 11,
    rarity: 'RARE',
    category: '풍경',
    owner: '코드잇',
    description: "How Far I'll Go",
    price: '4 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 12,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '스페인 여행',
    price: '4 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-two.svg',
  },
  {
    id: 13,
    rarity: 'RARE',
    category: '풍경',
    owner: '코드잇',
    description: "How Far I'll Go",
    price: '4 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 14,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '스페인 여행',
    price: '4 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-two.svg',
  },
  {
    id: 15,
    rarity: 'COMMON',
    category: '풍경',
    owner: '미쓰손',
    description: '우리집 앞마당',
    price: '4 P',
    remaining: 0,
    outof: 5,
    imageSrc: '/assets/products/photo-card-soldout.svg',
  },
  {
    id: 16,
    rarity: 'RARE',
    category: '여행',
    owner: '미쓰손',
    description: '도쿄 야경',
    price: '5 P',
    remaining: 1,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 17,
    rarity: 'COMMON',
    category: '풍경',
    owner: '코드잇',
    description: '한강 노을',
    price: '3 P',
    remaining: 3,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 18,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '파리 에펠탑',
    price: '6 P',
    remaining: 1,
    outof: 5,
    imageSrc: '/assets/products/photo-card-two.svg',
  },
  {
    id: 19,
    rarity: 'LEGENDARY',
    category: '풍경',
    owner: '미쓰손',
    description: '알프스 설산',
    price: '10 P',
    remaining: 0,
    outof: 5,
    imageSrc: '/assets/products/photo-card-soldout.svg',
  },
  {
    id: 20,
    rarity: 'COMMON',
    category: '여행',
    owner: '코드잇',
    description: '부산 바다',
    price: '3 P',
    remaining: 4,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 21,
    rarity: 'RARE',
    category: '풍경',
    owner: '코드잇덕후',
    description: '가을 숲길',
    price: '5 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 22,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '미쓰손',
    description: '뉴욕 타임스퀘어',
    price: '6 P',
    remaining: 1,
    outof: 5,
    imageSrc: '/assets/products/photo-card-two.svg',
  },
  {
    id: 23,
    rarity: 'COMMON',
    category: '풍경',
    owner: '코드잇',
    description: '비 오는 창가',
    price: '3 P',
    remaining: 5,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 24,
    rarity: 'RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '이탈리아 골목',
    price: '5 P',
    remaining: 2,
    outof: 5,
    imageSrc: '/assets/products/photo-card-another.svg',
  },
  {
    id: 25,
    rarity: 'LEGENDARY',
    category: '풍경',
    owner: '미쓰손',
    description: '사막의 별',
    price: '10 P',
    remaining: 0,
    outof: 5,
    imageSrc: '/assets/products/photo-card-soldout.svg',
  },
];
